language: haskell
ghc:
  - "8.0"
  - "7.10"
  
before_install:
  - cabal install happy

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test
  
after_script:
  - cabal install codecov-haskell
  - codecov-haskell Tests
